[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/toqueteos/webbrowser"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"
